1. Crie dois NumPy Arrays unidimensionais de tamanho 8: um formado apenas por 1’s e outro formado por números aleatórios entre 0 e 9. Some estes dois NumPy Arrays e guarde o resultado dentro de um terceiro NumPy Array. Por fim, faça o seguinte:

a) Se a soma de todos os elementos do Array resultante for >= 40, remodele este NumPy Array para se tornar uma matriz com mais linhas do que colunas. Senão, remodele para que se torne uma matriz com mais colunas do que linhas.

In [22]:
import numpy as np

array1 = np.ones(8)
array2 = np.random.randint(0, 10, 8)

array3 = array1 + array2

soma_total = np.sum(array3)

if soma_total >= 40:
    array_remodelado = array3.reshape(4, 2)
else:
    array_remodelado = array3.reshape(2, 4)

print(f"Array aleatório: {array2}")
print(f"Soma total: {soma_total}")
print(f"Array remodelado:\n {array_remodelado}")

Array aleatório: [3 0 4 6 6 4 0 7]
Soma total: 38.0
Array remodelado:
 [[4. 1. 5. 7.]
 [7. 5. 1. 8.]]


2. Crie dois NumPy Arrays unidimensionais: um de números pares de 0 à 51 e outro também de números pares de 100 até 50. Em seguida, os concatene e mostre os resultados ordenados.

In [23]:
import numpy as np

array1 = np.arange(0, 52, 2)
array2 = np.arange(100, 48, -2)

arr_concat = np.concatenate((array1, array2))

arr_ordenado = np.sort(arr_concat)

print(f"Array ordenada: {arr_ordenado}")

Array ordenada: [  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  50  52  54  56  58  60  62  64  66  68
  70  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


3. Mini Campo Minado

a) Crie um NumPy Array 2x2 formado apenas por 0’s.

b) Em seguida, adicione um número 1 em uma posição aleatória desta matriz.

c) Faça uma entrada de dados para solicitar ao usuário que faça uma jogada (selecione uma posição da matriz).

I. Se ele selecionar todas as posições em que o número 1 não se encontra, mostre a mensagem:
"Congratulations! You beat the game! :)"

II. Senão, se dentro das 3 primeiras jogadas ele achar o número 1, mostre a mensagem:
"Game Over! :( Try Again!"

In [43]:
import numpy as np

#a) Array 2x2 de zeros
campo = np.zeros((2, 2))

#b) Add número 1 em uma posição aleatória
linha_mina = np.random.randint(0, 2)
coluna_mina = np.random.randint(0, 2)
campo[linha_mina, coluna_mina] = 1

#c) Usuário informa posição
linha = int(input("Digite a linha (0 ou 1): "))
coluna = int(input("Digite a coluna (0 ou 1): "))

for tentativa in range(1, 4):
    if campo[linha, coluna] == 1:
        print(f"Game Over! :( Try Again!")
        break
    elif tentativa == 3:
        print("Congratulations! You beat the game! :)")
    else:
        linha = int(input("Digite a linha (0 ou 1): "))
        coluna = int(input("Digite a coluna (0 ou 1): "))

Congratulations! You beat the game! :)


4. Crie uma matriz de tamanho qualquer. Extraia seu número de linhas e colunas, multiplique-os, e diga se esta matriz poderia se tornar um vetor unidimensional com número par ou ímpar de elementos.

In [44]:
import numpy as np

matriz = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

num_linhas, num_colunas = matriz.shape
total_elementos = num_linhas * num_colunas

if total_elementos % 2 == 0:
    print(f"A matriz possui {total_elementos} elementos, que é um número par.")
else:
    print(f"A matriz possui {total_elementos} elementos, que é um número ímpar.")

A matriz possui 12 elementos, que é um número par.


5. Crie uma matriz de tamanho 4x4 formada por números aleatórios inteiros entre 1 e 50 (use seed = 10 antes):

a) Mostre o resultado da média de cada linha e cada coluna da matriz gerada.

b) Apresente o maior valor das médias das linhas e também das colunas.

c) Mostre a quantidade de aparições de cada um dos números gerados na matriz. Em seguida, mostre apenas os números que aparecem 2 vezes.

In [45]:
import numpy as np

np.random.seed(10)
matriz = np.random.randint(1, 51, size=(4, 4))

# a) Cálculo da média de cada linha e de cada coluna
medias_linhas = np.mean(matriz, axis=1)
medias_colunas = np.mean(matriz, axis=0)
print("\nMédia de cada linha:")
print(medias_linhas)
print("\nMédia de cada coluna:")
print(medias_colunas)

# b) Maior valor das médias das linhas e das colunas
max_media_linha = np.max(medias_linhas)
max_media_coluna = np.max(medias_colunas)
print("\nMaior média entre as linhas:", max_media_linha)
print("Maior média entre as colunas:", max_media_coluna)

# c) Quantidade de aparições de cada número na matriz
numeros, contagens = np.unique(matriz, return_counts=True)
frequencia = dict(zip(numeros, contagens))
print("\nFrequência de cada número na matriz:")
print(frequencia)

# Exibir apenas os números que aparecem exatamente 2 vezes
numeros_2_vezes = [num for num, freq in frequencia.items() if freq == 2]
print("\nNúmeros que aparecem exatamente 2 vezes:")
print(numeros_2_vezes)


Média de cada linha:
[16.   33.75 34.5  23.75]

Média de cada coluna:
[29.75 24.25 33.75 20.25]

Maior média entre as linhas: 34.5
Maior média entre as colunas: 33.75

Frequência de cada número na matriz:
{np.int32(1): np.int64(2), np.int32(9): np.int64(1), np.int32(10): np.int64(2), np.int32(16): np.int64(1), np.int32(26): np.int64(1), np.int32(29): np.int64(1), np.int32(30): np.int64(2), np.int32(37): np.int64(1), np.int32(41): np.int64(1), np.int32(43): np.int64(1), np.int32(49): np.int64(1), np.int32(50): np.int64(2)}

Números que aparecem exatamente 2 vezes:
[np.int32(1), np.int32(10), np.int32(30), np.int32(50)]
